---
- name: imagemagick and font installed
  yum: name={{ item }} state=latest
  with_items:
    - "ImageMagick"
    - "ImageMagick-devel"
    - "ipa-pgothic-fonts"

# create redmine directories
- include: create_redmine_directories.yml
