---
- name: imagemagick and font installed
  yum: name={{ item }} state=latest
  with_items:
    - "ImageMagick"
    - "ImageMagick-devel"
    - "ipa-pgothic-fonts"

- name: bundler installed.
  become: yes
  become_user: "{{redmine.user}}"
  command: "gem install bundler"

# create redmine directories
- include: create_redmine_directories.yml

# bundle
- name: Bundle
  shell: bash -lc "cd {{redmine.root_dir}}/redmine; bundle install --without development test --path=vendor/bundle"
  become: yes
  become_user: "{{redmine.user}}"

- name: Generate secret_token
  shell: bash -lc "cd {{redmine.root_dir}}/redmine; bundle exec rake config/initializers/secret_token.rb"
  become: yes
  become_user: "{{redmine.user}}"

- name: Create redmine database and load default data
  shell: bash -lc "cd {{redmine.root_dir}}/redmine; bundle exec rake db:create RAILS_ENV=production; bundle exec rake db:migrate RAILS_ENV=production; bundle exec rake redmine:load_default_data RAILS_ENV=production REDMINE_LANG=ja"
  become: yes
  become_user: "{{redmine.user}}"

- name: Install redmine init script
  template: src=unicorn_redmine.j2 dest=/etc/init.d/redmine mode=0755

- name: remove config.ru on Redmine root
  file: path=/var/rails/redmine/config.ru state=absent

- name: add configuration.yml
  template: src=configuration.yml.j2 dest=/var/rails/shared/config/configuration.yml

- name: Start redmine
  service: name=redmine state=restarted enabled=yes
