---
- name: yum update all
  yum: name=* state=latest

- name: install MySQL Yum Repository
  yum: name={{ mysql56.repository_url }}

- name: install MySQL/MySQL-python/libselinux-python
  yum: name={{ item.name }} enablerepo={{ item.repo }} state=present
  enablerepo: mysql56-community
  disablerepo: mysql57-community
  with_items:
    - { name: "mysql-community-libs-compat", repo: "mysql57-community" }
    - { name: "mysql-community-client", repo: "mysql57-community" }
    - { name: "mysql-community-server", repo: "mysql57-community" }
    - { name: "MySQL-python", repo: "epel" }
    - { name: "libselinux-python", repo: "epel" }

- name: add my.cnf character-set-server
  replace: dest=/etc/my.cnf regexp="^\[mysqld\]$" replace="[mysqld]\ncharacter-set-server=utf8"

- name: start MySQL service
  service: name=mysqld enabled=yes state=started
